import matplotlib.pyplot as plt

def plot(log):
    plt.figure()
    ax = plt.subplot(331)
    plt.style.use("seaborn-whitegrid")
    plt.plot(log["t"], log["x"][:, 0], "b", linewidth=2)
    plt.axhline(y=log["xd"][0], color="r", linestyle="-", linewidth=2)
    plt.axhline(y=-1.0, color="k", linestyle="--")
    plt.axhline(y=1.0, color="k", linestyle="--")
    plt.gca().set_title("$${x_Q}_x$$")
    plt.grid(visible=True, which="major", color="#666666", linestyle="-")
    plt.minorticks_on()
    plt.grid(visible=True, which="minor", color="#999999", linestyle=":")

    plt.subplot(332)
    plt.style.use("seaborn-whitegrid")
    plt.plot(log["t"], log["x"][:, 1], "b", linewidth=2)
    plt.axhline(y=log["xd"][1], color="r", linestyle="-", linewidth=2)
    plt.axhline(y=-1.0, color="k", linestyle="--")
    plt.axhline(y=1.0, color="k", linestyle="--")
    # plt.legend(['$$q_y$$'])
    plt.gca().set_title("$${x_Q}_y$$")
    plt.grid(visible=True, which="major", color="#666666", linestyle="-")
    plt.minorticks_on()
    plt.grid(visible=True, which="minor", color="#999999", linestyle=":")

    plt.subplot(333)
    plt.style.use("seaborn-whitegrid")
    plt.plot(log["t"], log["x"][:, 2], "b", linewidth=2)
    plt.axhline(y=log["xd"][2], color="r", linestyle="-", linewidth=2)
    plt.axhline(y=-1.0, color="k", linestyle="--")
    plt.axhline(y=1.0, color="k", linestyle="--")
    plt.gca().set_title("$${x_Q}_z$$")
    plt.grid(visible=True, which="major", color="#666666", linestyle="-")
    plt.minorticks_on()
    plt.grid(visible=True, which="minor", color="#999999", linestyle=":")

    plt.subplot(334)
    plt.style.use("seaborn-whitegrid")
    plt.plot(log["t"], log["x"][:, 3], "b", linewidth=2)
    plt.axhline(y=log["xd"][3], color="r", linestyle="-")
    plt.gca().set_title("$${v_Q}_x$$")
    plt.grid(visible=True, which="major", color="#666666", linestyle="-")
    plt.minorticks_on()
    plt.grid(visible=True, which="minor", color="#999999", linestyle=":")

    plt.subplot(335)
    plt.style.use("seaborn-whitegrid")
    plt.plot(log["t"], log["x"][:, 4], "b", linewidth=2)
    plt.axhline(y=log["xd"][4], color="r", linestyle="-")
    plt.gca().set_title("$${v_Q}_y$$")
    plt.grid(visible=True, which="major", color="#666666", linestyle="-")
    plt.minorticks_on()
    plt.grid(visible=True, which="minor", color="#999999", linestyle=":")

    plt.subplot(336)
    plt.style.use("seaborn-whitegrid")
    plt.plot(log["t"], log["x"][:, 5], "b", linewidth=2)
    plt.axhline(y=log["xd"][5], color="r", linestyle="-")
    plt.gca().set_title("$${v_Q}_z$$")
    plt.grid(visible=True, which="major", color="#666666", linestyle="-")
    plt.minorticks_on()
    plt.grid(visible=True, which="minor", color="#999999", linestyle=":")

    plt.subplot(337)
    plt.style.use("seaborn-whitegrid")
    plt.plot(log["t"][:-1], log["u"][:, 0], "b", linewidth=1)
    plt.gca().set_title("$$f_x$$")
    plt.grid(visible=True, which="major", color="#666666", linestyle="-")
    plt.minorticks_on()
    plt.grid(visible=True, which="minor", color="#999999", linestyle=":")

    plt.subplot(338)
    plt.style.use("seaborn-whitegrid")
    plt.plot(log["t"][:-1], log["u"][:, 1], "b", linewidth=1)
    plt.gca().set_title("$$f_y$$")
    plt.grid(visible=True, which="major", color="#666666", linestyle="-")
    plt.minorticks_on()
    plt.grid(visible=True, which="minor", color="#999999", linestyle=":")

    plt.subplot(339)
    plt.style.use("seaborn-whitegrid")
    plt.plot(log["t"][:-1], log["u"][:, 2], "b", linewidth=1)
    plt.gca().set_title("$$f_z$$")
    plt.grid(visible=True, which="major", color="#666666", linestyle="-")
    plt.minorticks_on()
    plt.grid(visible=True, which="minor", color="#999999", linestyle=":")

    plt.show()